name: build

on:
  push:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Install OS Dependencies
        run: |
          sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install Analyzer Dependencies
        run: make check_deps

      - name: Lint golangci-lint
        run: make link_golangci

      - name: Lint vet
        run: make lint_vet

      - name: Lint imports
        run: make lint_imports

      - name: Lint cyclo
        run: make lint_cyclo

      - name: Lint golint
        run: make lint_golint

      - name: Lint static
        run: make link_golangci

  test:
    runs-on: ubuntu-latest
    name: Test
    environment: release
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get dependencies
        run: |
          sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
          cache: true

      - name: Test
        run: make test
