name: build

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: false
          args: --disable unused

      - name: Build
        run: go build -o bd_test
