name: build

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Get dependencies
        run: |
          sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@v0.2.1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Lint
        run: make lint

      - name: Build
        run: go build -o bd_test
